### ISSUE TITLE
Estimating safe transactions fails after 10 minutes, then starts working again

### ISSUE THREAD

**Issue by jurgenwerk** [5afe/safe-relay-service#528]
**Describe the bug**

Every 10 minutes of relay server inactivity, we get a "Connection aborted" error when issuing a request to estimate a safe transaction. 

```
2023-01-19 18:52:40,748 [WARNING] [MainProcess] https://relay-goerli.staging.stack.cards/api/v2/safes/0x075531A656A7acc46abb5b69Bb459Fd3eE923B22/transactions/estimate/
  Exception: ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) - Data received {
   'to': '0x7a8FD557D806feaf3235773201b82A616CA5cf28',
   'value': '0',
   'data': '0x7d37d97e5f3d6a1050da6134c241a632e17ae7c52d6db848160c7b9d634928264db9e9a0',
   'operation': 0,
   'gas_token': '0x07865c6E87B9F70255377e024ace6630C1Eaa37F',
   'safe': '0x075531A656A7acc46abb5b69Bb459Fd3eE923B22'
  }
```

Full log and stack trace from the server:

```
2023-01-19 18:52:40,748 [WARNING] [MainProcess] https://relay-goerli.staging.stack.cards/api/v2/safes/0x075531A656A7acc46abb5b69Bb459Fd3eE923B22/transactions/estimate/
  Exception: ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) - Data received {
   'to': '0x7a8FD557D806feaf3235773201b82A616CA5cf28',
   'value': '0',
   'data': '0x7d37d97e5f3d6a1050da6134c241a632e17ae7c52d6db848160c7b9d634928264db9e9a0',
   'operation': 0,
   'gas_token': '0x07865c6E87B9F70255377e024ace6630C1Eaa37F',
   'safe': '0x075531A656A7acc46abb5b69Bb459Fd3eE923B22'
  }
Traceback (most recent call last)
File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen                                                                                          
    httplib_response = self._make_request(                                                                                                                                                
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request                                                                                    
    six.raise_from(e, None)                                                                                                                                                               
  File "<string>", line 3, in raise_from                                                                                                                                                  
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request                                                                                    
    httplib_response = conn.getresponse()                                                                                                                                                 
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse                                                                                                              
    response.begin()                                                                                                                                                                      
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin                                                                                                                     
    version, status, reason = self._read_status()                                                                                                                                         
  File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status                                                                                                              
    raise RemoteDisconnected("Remote end closed connection without"                                                                                                                       
http.client.RemoteDisconnected: Remote end closed connection without response                                                                                                             
During handling of the above exception, another exception occurred:                                                                                                                       
Traceback (most recent call last):                                                                                                                                                        
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send                                                                                                  
    resp = conn.urlopen(                                                                                                                                                                  
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen                                                                                          
    retries = retries.increment(                                                                                                                                                          
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment                                                                                            
    raise six.reraise(type(error), error, _stacktrace)                                                                                                                                    
  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise                                                                                            
    raise value.with_traceback(tb)                                                                                                                                                        
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen                                                                                          
    httplib_response = self._make_request(                                                                                                                                                
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request                                                                                    
    six.raise_from(e, None)                                                                                                                                                               
  File "<string>", line 3, in raise_from                                                                                                                                                  
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request                                                                                    
    httplib_response = conn.getresponse()                                                                                                                                                 
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse                                                                                                              
    response.begin()                                                                                                                                                                      
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin                                                                                                                     
    version, status, reason = self._read_status()                                                                                                                                         
  File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status                                                                                                              
    raise RemoteDisconnected("Remote end closed connection without"                                                                                                                       
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))                                                            
During handling of the above exception, another exception occurred:                                                                                                                       
Traceback (most recent call last):                                                                                                                                                        
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch                                                                                           
    response = handler(request, *args, **kwargs)                                                                                                                                          
  File "/app/safe_relay_service/relay/views_v2.py", line 149, in post                                                                                                                     
    transaction_estimation = TransactionServiceProvider().estimate_tx(                                                                                                                    
  File "/app/safe_relay_service/relay/services/transaction_service.py", line 275, in estimate_tx                                                                                          
    safe_tx_gas = safe.estimate_tx_gas(to, value, data, operation)                                                                                                                        
  File "/usr/local/lib/python3.10/site-packages/gnosis/safe/safe.py", line 824, in estimate_tx_gas                                                                                        
    self.estimate_tx_gas_by_trying(to, value, data, operation)                                                                                                                            
  File "/usr/local/lib/python3.10/site-packages/gnosis/safe/safe.py", line 765, in estimate_tx_gas_by_trying                                                                              
    gas_estimated = self.estimate_tx_gas_with_safe(to, value, data, operation)                                                                                                            
  File "/usr/local/lib/python3.10/site-packages/gnosis/safe/safe.py", line 708, in estimate_tx_gas_with_safe                                                                              
    response = self.ethereum_client.http_session.post(                                                                                                                                    
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 635, in post                                                                                                  
    return self.request("POST", url, data=data, json=json, **kwargs)                                                                                                                      
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request                                                                                               
    resp = self.send(prep, **send_kwargs)                                                                                                                                                 
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send                                                                                                  
    r = adapter.send(request, **kwargs)                                                                                                                                                   
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 547, in send                                                                                                  
    raise ConnectionError(err, request=request)                                                                                                                                           
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))                                                         
Internal Server Error: /api/v2/safes/0x075531A656A7acc46abb5b69Bb459Fd3eE923B22/transactions/estimate/                                                                                    
2023-01-19 18:52:40,750 [ERROR] [MainProcess] Internal Server Error: /api/v2/safes/0x075531A656A7acc46abb5b69Bb459Fd3eE923B22/transactions/estimate/    
```

**To Reproduce**

First request after 10 mins of inactivity fails:

```
curl 'https://relay-goerli.staging.stack.cards/api/v2/safes/0x3C76766cd63208E9D8db91c09743B4aeebFeb86b/transactions/estimate/' \
  -H 'authority: relay-goerli.staging.stack.cards' \
  -H 'accept: application/json' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'content-type: application/json' \
  -H 'origin: https://safe-tools-staging.stack.cards' \
  -H 'referer: https://safe-tools-staging.stack.cards/' \
  -H 'sec-ch-ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36' \
  --data-raw '{"to":"0x4a96dF5bc39D9192e5f28604fad5B65a3098c145","value":"0","data":"0x7d37d97e0064df71b44d1801eb0fccffd91b18297642a3f6f23d865385933c778045f4e2","operation":0,"gasToken":"0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6"}' \
  --compressed
  
{"exception":"ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"}%
```

2nd request right after the previous one succeeds:

```
❯ curl 'https://relay-goerli.staging.stack.cards/api/v2/safes/0x3C76766cd63208E9D8db91c09743B4aeebFeb86b/transactions/estimate/' \
  -H 'authority: relay-goerli.staging.stack.cards' \
  -H 'accept: application/json' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'content-type: application/json' \
  -H 'origin: https://safe-tools-staging.stack.cards' \
  -H 'referer: https://safe-tools-staging.stack.cards/' \
  -H 'sec-ch-ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36' \
  --data-raw '{"to":"0x4a96dF5bc39D9192e5f28604fad5B65a3098c145","value":"0","data":"0x7d37d97e0064df71b44d1801eb0fccffd91b18297642a3f6f23d865385933c778045f4e2","operation":0,"gasToken":"0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6"}' \
  --compressed
  
{"safeTxGas":"112732","baseGas":"48660","dataGas":"48660","operationalGas":"0","gasPrice":"1048441145","lastUsedNonce":0,"gasToken":"0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6","refundReceiver":"0xD7182E380b7dFa33C186358De7E1E5d0950fCAE7"}%
```

**Expected behavior**
It shouldn't fail after 10 minutes of inactivity (when no requests are sent to the relay server). I tried using different ethereum nodes but it didn't help. Any ideas?

**Comment by Uxio0** [comment]
Hi, we didn't experience that when we were running the relay. Also, timeout for the relay connection to the node it's really small (15 seconds), so those 10 minutes it's not anything that rings a bell from my side. You should check your server, maybe connections are killed after that time (service maintains a http session so if it's killed you will get an error like that)

**Comment by jurgenwerk** [comment]
@Uxio0 thanks. I tested the same setup locally and it works fine, it only happens in my deployment environment. So perhaps it really is a server issue - I'll take a closer look.

**Comment by Uxio0** [comment]
Good to hear that @jurgenwerk
